### PR TITLE
WIP update pre-commit hooks, ignoring the binary

### PR DESCRIPTION
**Pull request by goern**
Signed-off-by: Christoph Görn <goern@redhat.com>

### CODE REVIEW

**Comment by larsks** [comment]
That seems identical to what we already have, except that the pre-commit hook repositories have been updated (see e.g. https://github.com/operate-first/opfcli/blob/main/.pre-commit-config.yaml and the adjacent .prow.yaml).

The thoth-precommit image doesn't have `go` or any of the associated tooling; it just blows up when it hits the go-related CI checks. That's why I ended up building a custom image for both the pre-commit and release workflow.

**Comment by goern** [comment]
Well, ja, it migrated the pre-commit from github action to prow job

So you say the go tooling is not installed with the pre-commit hook installment?

**Comment by larsks** [comment]
> So you say the go tooling is not installed with the pre-commit hook installment?

Right. Pre-commit generally doesn't install system binaries; it just installs scripts that expect the binary tools to already be in place.

**Comment by larsks** [comment]
Closing because this conversation is happening in too many places :). Maybe we will continue in https://github.com/thoth-station/thoth-ops-infra/issues/38.

**Pull request closed without merging**
